name: Auto-approve PRs

on:
  pull_request:
    types:
      - opened

jobs:
  auto_approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto-approve PR
        uses: peter-evans/auto-approve@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-token: ${{ github.token }}
          #approvals-count: 1
          request-changes: false